# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

stages:
- stage: PublishArtifact
  displayName: Publish template files as artifact
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
    - job: PublishArtifact
      displayName: Copy and publish artifact
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
- stage: Dev
  displayName: 'Deploy to dev'
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    - group: DevGroup
  jobs:
    - deployment: DeployInfrastructure
      displayName: 'Deploy ARM template'
      environment: DevEnv
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureResourceManagerTemplateDeployment@3
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: 'Azure'
                  subscriptionId: 'befef620-bbb0-446e-8a94-a11b1fdd4c8e'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: 'TestIaCPipeline-Dev'
                  location: 'Australia East'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(Agent.BuildDirectory)/drop/template.json'
                  csmParametersFile: '$(Agent.BuildDirectory)/drop/parameters.json'
                  overrideParameters: '-environment $(Environment)'
                  deploymentMode: 'Incremental'
- stage: Test
  displayName: 'Deploy to test'
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    - group: TestGroup
  jobs:
    - deployment: DeployInfrastructure
      displayName: 'Deploy ARM template'
      environment: TestEnv
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureResourceManagerTemplateDeployment@3
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: 'Azure'
                  subscriptionId: 'befef620-bbb0-446e-8a94-a11b1fdd4c8e'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: 'TestIaCPipeline-Test'
                  location: 'Australia East'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(Agent.BuildDirectory)/drop/template.json'
                  csmParametersFile: '$(Agent.BuildDirectory)/drop/parameters.json'
                  overrideParameters: '-environment $(Environment)'
                  deploymentMode: 'Incremental'


  






